server:
  port: 8085


spring:
  application:
    name: CONFIG-SERVER


  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChandradipMoonlight/common-configuration-hrs
          clone-on-start: true

